### ISSUE TITLE
Markup Issue

### ISSUE THREAD

**Issue by NikolaySav** [64robots/nova-json#12]
Hello!

Using your package i've encountered a markup issue with longish json key names.
Screenshot attached.

<img width="387" alt="screenshot at sep 22 00-23-56" src="https://user-images.githubusercontent.com/13363510/45906805-2a128600-bdfe-11e8-86a4-4210f8ba2aed.png">

**Comment by beliolfa** [comment]
This package has been merged into https://github.com/64robots/nova-fields. Feel free to reopen this issue there if still happen.
