### ISSUE TITLE
Error when value is null

### ISSUE THREAD

**Issue by dthvega** [64robots/nova-json#8]
An error gets returned if the value is null in the Resolve method:
`json_decode() expects parameter 1 to be string, array given`
In
`$this->value = is_object($value) ? $value : json_decode($value);`

**Comment by beliolfa** [comment]
Can't reproduce. Could you give a more detailed example?

**Comment by dthvega** [comment]
Apologies, I misinterpret the error.
I see the resolve method does not use the callback for the resolveUsing().
In the previous release it used the parent (field) resolve that is why it used the callback.

**Comment by beliolfa** [comment]
I close it then. Feel free to reopen if you still having issues.
